"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { usePathname } from "next/navigation";

/*
  NIDAN REPORT BARCODE
  - Code 39, rendered as SVG so it stays sharp in A4 PDF/print.
  - Uses the report number already generated by the report workflow.
  - Injects into the existing A4 report without changing report data.
*/

const CODE39 = {
  "0": "101001101101",
  "1": "110100101011",
  "2": "101100101011",
  "3": "110110010101",
  "4": "101001101011",
  "5": "110100110101",
  "6": "101100110101",
  "7": "101001011011",
  "8": "110100101101",
  "9": "101100101101",
  A: "110101001011",
  B: "101101001011",
  C: "110110100101",
  D: "101011001011",
  E: "110101100101",
  F: "101101100101",
  G: "101010011011",
  H: "110101001101",
  I: "101101001101",
  J: "101011001101",
  K: "110101010011",
  L: "101101010011",
  M: "110110101001",
  N: "101011010011",
  O: "110101101001",
  P: "101101101001",
  Q: "101010110011",
  R: "110101011001",
  S: "101101011001",
  T: "101011011001",
  U: "110010101011",
  V: "100110101011",
  W: "110011010101",
  X: "100101101011",
  Y: "110010110101",
  Z: "100110110101",
  "-": "100101011011",
  ".": "110010101101",
  " ": "100110101101",
  $: "100100100101",
  "/": "100100101001",
  "+": "100101001001",
  "%": "101001001001",
  "*": "100101101101",
};

function cleanCode39(value) {
  const cleaned = String(value || "")
    .toUpperCase()
    .replace(/[^0-9A-Z.\- $/+%]/g, "")
    .trim();

  return cleaned || "NIDAN-REPORT";
}

function barcodeModules(value) {
  const text = `*${cleanCode39(value)}*`;
  const modules = [];

  [...text].forEach((character, charIndex) => {
    const pattern = CODE39[character] || CODE39["-"];

    [...pattern].forEach((bit) => {
      modules.push(bit === "1");
    });

    if (charIndex < text.length - 1) {
      modules.push(false);
    }
  });

  return modules;
}

function ReportBarcode({ value }) {
  const modules = useMemo(() => barcodeModules(value), [value]);
  const width = modules.length;
  const height = 54;

  return (
    <div className="nidan-report-barcode" aria-label={`Report barcode ${value}`}>
      <div className="nidan-report-barcode-label">REPORT BARCODE</div>
      <svg
        className="nidan-report-barcode-svg"
        viewBox={`0 0 ${width} ${height}`}
        role="img"
        aria-label={`Barcode for report ${value}`}
        preserveAspectRatio="none"
      >
        <rect x="0" y="0" width={width} height={height} fill="#ffffff" />
        {modules.map((isBar, index) =>
          isBar ? (
            <rect key={index} x={index} y="2" width="1" height="36" fill="#101828" />
          ) : null
        )}
      </svg>
      <div className="nidan-report-barcode-value">{value}</div>
    </div>
  );
}

export default function NidanReportBarcodeEnhancer() {
  const pathname = usePathname();
  const [target, setTarget] = useState(null);
  const [reportNo, setReportNo] = useState("");

  const isReportRoute =
    pathname === "/report" ||
    pathname?.startsWith("/reports/");

  useEffect(() => {
    if (!isReportRoute) {
      setTarget(null);
      return undefined;
    }

    const readReportNumber = () => {
      let value = "";

      try {
        value = localStorage.getItem("nidanCurrentReportNo") || "";
      } catch {
        value = "";
      }

      if (!value) {
        const text = document.body?.innerText || "";
        const match = text.match(/NPL[-A-Z0-9.]+/i);
        value = match?.[0] || "";
      }

      setReportNo(value || "NPL-REPORT");
    };

    const findTarget = () => {
      const element =
        document.querySelector(".a4Page") ||
        document.querySelector(".reportPage");

      if (element) {
        setTarget(element);
      }

      readReportNumber();
    };

    findTarget();

    const observer = new MutationObserver(findTarget);
    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    const timer = window.setTimeout(findTarget, 250);

    return () => {
      observer.disconnect();
      window.clearTimeout(timer);
    };
  }, [isReportRoute, pathname]);

  if (!isReportRoute || !target || !reportNo) {
    return null;
  }

  return createPortal(
    <ReportBarcode value={reportNo} />,
    target
  );
}
